version: '3.8'

services:
  funding-rate-monitor:
    build: .
    container_name: binance-funding-monitor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://fapi.binance.com/fapi/v1/ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge